# Generated by Django 3.1.6 on 2021-02-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(auto_now=True, null=True, verbose_name='생년월일')),
                ('email', models.CharField(default='', max_length=255, verbose_name='이메일')),
                ('name', models.CharField(default='', max_length=255, null=True, verbose_name='이름')),
                ('gender', models.CharField(choices=[('여', '여자'), ('남', '남자')], default='여', max_length=255, null=True, verbose_name='성별')),
                ('refreshDate', models.DateField(auto_now=True, null=True, verbose_name='새로 고침 시각')),
                ('refreshToken', models.CharField(default='', max_length=255, null=True, verbose_name='이름')),
                ('imageUrl', models.URLField(default='', max_length=255, null=True, verbose_name='첨부 이미지파일 주소')),
                ('mission', models.TextField(default='', null=True, verbose_name='미션 JSON')),
                ('snsId', models.CharField(default='', max_length=255, verbose_name='소셜 아이디')),
                ('snsType', models.CharField(default='', max_length=255, verbose_name='소셜 타입')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='수정 날짜')),
            ],
            options={
                'verbose_name': '답변 목록',
                'verbose_name_plural': '답변 목록',
                'db_table': 'answers',
                'managed': False,
            },
        ),
    ]
