# Generated by Django 3.1.6 on 2021-02-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=255, verbose_name='질문 내용')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='수정 날짜')),
            ],
            options={
                'verbose_name': '질문 목록',
                'verbose_name_plural': '질문 목록',
                'db_table': 'questions',
                'managed': False,
            },
        ),
    ]
