# Generated by Django 3.1.6 on 2021-02-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardUrl', models.URLField(default='', max_length=255, verbose_name='파츠 PDF 주소')),
                ('cardSvgUrl', models.URLField(default='', max_length=255, verbose_name='파츠 SVG 주소')),
                ('cardPngUrl', models.URLField(default='', max_length=255, verbose_name='파츠 PNG 주소')),
                ('part', models.PositiveIntegerField(default=0, verbose_name='파츠 번호')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='수정 날짜')),
            ],
            options={
                'verbose_name': '파츠 목록',
                'verbose_name_plural': '파츠 목록',
                'db_table': 'files',
                'managed': False,
            },
        ),
    ]
